In [1]:
#a slow but sustainble process is needed for me
#so i will start learning today
#some of the contents come from Internet,i wrote it just for myself
#20201210 Dalian

In [2]:
#载入torch
import torch

In [3]:
#创建一个未初始化的5x3张量
x=torch.empty(5,3)
x

tensor([[9.2755e-39, 1.0561e-38, 4.5001e-39],
        [4.9592e-39, 4.8674e-39, 4.2246e-39],
        [1.0286e-38, 1.0653e-38, 1.0194e-38],
        [8.4490e-39, 1.0469e-38, 9.3674e-39],
        [9.9184e-39, 8.7245e-39, 9.2755e-39]])

In [4]:
#创建一个随机的张量，其值在0到1之间
x=torch.rand(5,3)
x
#torch.float32
#可通过x.dtype获得

tensor([[0.9009, 0.7401, 0.7701],
        [0.0053, 0.9676, 0.0085],
        [0.1120, 0.8525, 0.2970],
        [0.7305, 0.4889, 0.5521],
        [0.8429, 0.6375, 0.1248]])

In [5]:
x=torch.zeros(5,3,dtype=torch.float64)
x
#也有torch.ones

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [6]:
#直接从数组获得张量
x=torch.tensor([[5,3],[1,2]])
x
#x.dtype is torch.int64

tensor([[5, 3],
        [1, 2]])

In [7]:
#从已有张量获取新张量
y=torch.randint_like(x,high=100)
y
#rand(区间随机)，randn(正态)

tensor([[87, 39],
        [93, 43]])

In [8]:
#返回张量的size
print(y.size())
print(y.size)

torch.Size([2, 2])
<built-in method size of Tensor object at 0x000001828012C340>


In [9]:
#加的三种写法
print(x+y)
z=torch.zeros_like(x)
torch.add(x,y,out=z)
print(z)
x.add_(y)

tensor([[92, 42],
        [94, 45]])
tensor([[92, 42],
        [94, 45]])


tensor([[92, 42],
        [94, 45]])

In [10]:
print(z[0,:])
print(z[:,1])

tensor([92, 42])
tensor([42, 45])


In [11]:
x=torch.randn(3,3)
y=x.view(-1)
y
#pytorch中的view类似于numpy中的reshape

tensor([-0.7454,  0.6813,  0.2490, -0.6577, -0.4186,  0.6003,  0.9654, -0.2390,
         0.0580])

In [12]:
#取出数字，只能对单位张量使用
print(x[0,0])
print(x[0,0].item())

tensor(-0.7454)
-0.745448112487793


In [13]:
#到numpy的转换
x=torch.rand(2,3)
y=x.numpy()
y

array([[0.5654776 , 0.09396446, 0.3307743 ],
       [0.12376273, 0.96479946, 0.22891533]], dtype=float32)

In [14]:
#观察x，y值的变化
x.add_(1)
#若使用x=x+1,则结果不同
print(x)
print(y)

tensor([[1.5655, 1.0940, 1.3308],
        [1.1238, 1.9648, 1.2289]])
[[1.5654776 1.0939645 1.3307743]
 [1.1237627 1.9647994 1.2289153]]


In [15]:
#观察其id
print(id(x))
print(id(y))
x=x+1
print(id(x))
x.add_(1)
print(id(x))

1660006123200
1660006115248
1660006151232
1660006151232


In [16]:
import numpy as np

In [17]:
a=np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
#numpy到张量的转化
b=torch.from_numpy(a)
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
#再次观察不同的加法的区别
print(id(a))
np.add(a,1,out=a)
print(id(a))
print(a)
print(b)

1660006117248
1660006117248
[[2. 2. 2.]
 [2. 2. 2.]]
tensor([[2., 2., 2.],
        [2., 2., 2.]], dtype=torch.float64)
