In [1]:
import torch
import numpy as np
import random
from matplotlib import pyplot as plt

In [2]:
num_inputs=2
num_examples=1000
true_w=[12.21,9.27]
true_b=1.08
features=torch.randn(num_examples,num_inputs,dtype=torch.float32)
labels=true_w[0]*features[:,0]+true_w[1]*features[:,1]+true_b
labels+=torch.normal(mean=torch.zeros_like(labels),std=0.1+torch.zeros_like(labels))

In [3]:
import torch.utils.data as Data

batch_size=10 #设置batch大小
dataset=Data.TensorDataset(features,labels) #传入数据，根据第一个维度进行打包
data_iter=Data.DataLoader(dataset,batch_size,shuffle=True) #迭代器，随机读取数据

In [4]:
import torch.nn as nn

In [5]:
net=nn.Sequential(
    nn.Linear(num_inputs,1)
    )

In [6]:
print(net)
print(net[0])

Sequential(
  (0): Linear(in_features=2, out_features=1, bias=True)
)
Linear(in_features=2, out_features=1, bias=True)


In [7]:
nn.init.normal_(net[0].weight,mean=0,std=0.1)
nn.init.constant_(net[0].bias,val=0)

Parameter containing:
tensor([0.], requires_grad=True)

In [8]:
#设置loss函数
loss = nn.MSELoss()

In [9]:
import torch.optim as optim
optimizer =optim.SGD(net.parameters(),lr=0.03)
print(optimizer)

SGD (
Parameter Group 0
    dampening: 0
    lr: 0.03
    momentum: 0
    nesterov: False
    weight_decay: 0
)


In [10]:
num_epochs = 3
for epoch in range(1, num_epochs + 1):
    for X, y in data_iter:
        output = net(X)
        l = loss(output, y.view(-1, 1))
        optimizer.zero_grad() # 梯度清零，等价于net.zero_grad()
        l.backward()
        optimizer.step()
    print('epoch %d, loss: %f' % (epoch, l.item()))

epoch 1, loss: 0.014356
epoch 2, loss: 0.011415
epoch 3, loss: 0.007247


P:\ana\lib\site-packages\torch\autograd\__init__.py:130: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 9000). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at  ..\c10\cuda\CUDAFunctions.cpp:100.)
  Variable._execution_engine.run_backward(


In [11]:
dense = net[0]
print(true_w, dense.weight)
print(true_b, dense.bias)


[12.21, 9.27] Parameter containing:
tensor([[12.2116,  9.2745]], requires_grad=True)
1.08 Parameter containing:
tensor([1.0836], requires_grad=True)
