In [1]:
#Pytorch张量自动微分
#20201211 Dalian

In [2]:
import torch

In [3]:
x=torch.ones(2,2,requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [4]:
y=x+2
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [5]:
z=y*y*3
out=z.mean()
print(z)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


In [6]:
out.backward()

P:\ana\lib\site-packages\torch\autograd\__init__.py:130: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 9000). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at  ..\c10\cuda\CUDAFunctions.cpp:100.)
  Variable._execution_engine.run_backward(


In [7]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [8]:
x = torch.ones(3, requires_grad=True)
x 

tensor([1., 1., 1.], requires_grad=True)

In [9]:
y=x*x*x
y

tensor([1., 1., 1.], grad_fn=<MulBackward0>)

In [10]:
v=torch.tensor([1,0.1,10])
v

tensor([ 1.0000,  0.1000, 10.0000])

In [11]:
y.backward(v)

In [12]:
x.grad

tensor([ 3.0000,  0.3000, 30.0000])